# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
