# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:28
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import planner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_origin', models.TimeField()),
                ('hour_destination', models.TimeField()),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('order', models.PositiveIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_destination', to='cities_light.City')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_origin', to='cities_light.City')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.AddField(
            model_name='poolinguser',
            name='birth_date',
            field=models.DateField(default=datetime.date(1999, 9, 27), validators=[planner.validators.validate_adult]),
        ),
        migrations.AddField(
            model_name='poolinguser',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please insert a valid cellphone number', regex='(\\+\\d{2}){0,1}3{1}\\d{9}')]),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_joinable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='max_num_passengers',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='poolinguser',
            name='driving_license',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='step',
            name='passengers',
            field=models.ManyToManyField(to='planner.PoolingUser'),
        ),
        migrations.AddField(
            model_name='step',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='planner.Trip'),
        ),
    ]
